ktor:
  application:
    modules: [ com.osucad.websocketgateway.ApplicationKt.production ]
  deployment:
    port: "$PORT:8080"


metrics:
  common-tags:
    service: "websocket-gateway"
    environment: "$SERVICE_ENVIRONMENT:production"
  datadog:
    uri: "$DATADOG_URI"
    api-key: "$DATADOG_API_KEY"